#+title: Rofi-Launcher

All I want from a tool like Rofi is the ability to find files or launch applications with a single keybind. For me, the key is the left super.
* Toggle the Rofi window
~launcher~ is a shell script that, when bound to a key, lets you toggle the Rofi window using only that key. What I wanted was to be able to press the super key a single time to invoke the launcher and interact with it. If, however, you press super a second time, the launcher is closed without doing anything. This functionality is provided by ~xdotool~. I recommend symlinking the launcher script somewhere that your window manager will find it, =~/.local/bin/launcher= for instance. Then you can bind the script in your window manager to the key of your choosing.
* Find files command
~find-in-home~ is another shell script that utilizes ~fd~ to provide a newline-delimited list of files in directories of your choosing. This can then be fed to Rofi so that you can use fuzzy-finding on just the filename without needing to remember exactly which directory you want. If you add or change directories in this script, follow the pattern of ~fd . [directory] ;~ to make things work smoothly.
* Bonus: Custom theme
This is my custom theme, based on the [[https://www.nordtheme.com/][Snow Storm]] color palette.
